UrbanRefuge.Web/Models/RefugeResources.cs
using System.Collections.Generic;



namespace UrbanRefuge.Web.Models
{
    public partial class RefugeResource
    {
        public RefugeResource()
        {
            ResourceTypes = new HashSet<RefugeResourceResourceType>();
            Languages = new HashSet<RefugeResourcesLanguage>();
        }

        public int ResourceId { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }

        public int? PrimaryResourceTypeId { get; set; }
        public virtual ResourceType PrimaryResourceType { get; set; }

        public virtual ICollection<RefugeResourceResourceType> ResourceTypes { get; set; }
        public virtual ICollection<RefugeResourcesLanguage> Languages { get; set; }
        
    }
}

UrbanRefuge.Web/Controllers/RefugeResourcesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata;
using System.IdentityModel;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UrbanRefuge.Web.Models;
using UrbanRefuge.Web.ViewModels;
using cloudscribe.Web.Pagination;
using Microsoft.AspNetCore.Authorization;

namespace UrbanRefuge.Web.Controllers
{
    [Authorize(ActiveAuthenticationSchemes = "Cookies", Policy = "Admin")]
    public class RefugeResourcesController : Controller
    {
        private const int DefaultPageSize = 15;
        private readonly RefugeResourceContext _context;

        public RefugeResourcesController(RefugeResourceContext context)
        {
            _context = context;
        }

        // GET: RefugeResources
        public async Task<IActionResult> Index(int? page, string query)
        {
            var refugeResources = _context.RefugeResources
                                            .Include(x => x.PrimaryResourceType)
                                            .Include(x => x.Languages)
                                            .Include(x => x.ResourceTypes)
                                            .AsQueryable();  //converts form includable to iquerable so can add search functionality


            var currentPageNum = page ?? 1;
            var offset = (DefaultPageSize * currentPageNum) - DefaultPageSize;

            var model = new RefugeResourcePagedViewModel();
            if (!String.IsNullOrEmpty(query))
            {
                refugeResources = refugeResources.Where(x => x.Languages.Any(l => l.Name.Contains(query)));
                model.Paging.TotalItems = refugeResources.Count();
            }

            model.Resources = await refugeResources.Skip(offset)
                                              .Take(DefaultPageSize)
                                              .Select(x => RefugeResourceViewModel.FromModel(x, SupportedCultures.GetCultureInfo(Contants.Arabic)))
                                              .ToListAsync();

            model.Paging.TotalItems = await refugeResources.CountAsync();
            model.Paging.CurrentPage = currentPageNum;
            model.Paging.ItemsPerPage = DefaultPageSize;
            model.Query = query;

            return View(model);
        }

        // GET: RefugeResources/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var refugeResource = await _context.RefugeResources
                                            .Include(x => x.PrimaryResourceType)
                                            .Include(x => x.Languages)
                                            .Include(x => x.ResourceTypes)
                                            .SingleOrDefaultAsync(x => x.ResourceId == id);


            if (refugeResource == null)
                return NotFound();

            var refugeResourceVm = RefugeResourceViewModel.FromModel(refugeResource, SupportedCultures.GetCultureInfo(Contants.Arabic));

            return View(refugeResourceVm);
        }

        // GET: RefugeResources/Create
        public IActionResult Create()
        {
            return View();
        }
        public static bool IsValidLatLong(double latitude, double longitude)
        {
            if (latitude < -90 || latitude > 90)
            {
                return false;
            }

            if (longitude < -180 || longitude > 180)
            {
                return false;
            }

            if (latitude == 0 && longitude == 0)
            {
                return false;
            }
            return true;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RefugeResourceViewModel refugeResource)
        {
            ValidateResource(refugeResource);

            if (ModelState.IsValid)
            {
                var resource = _context.RefugeResources.Add(new RefugeResource()
                {
                    Latitude = refugeResource.Posistion.Latitude,
                    Longitude = refugeResource.Posistion.Longitude,
                    PrimaryResourceTypeId = (int)refugeResource.PrimaryType,
                    Languages = new List<RefugeResourcesLanguage>()
                    {
                        new RefugeResourcesLanguage()
                        {
                            Address = refugeResource.ResourceLanguage1.Address,
                            DisplayType = LanguageDisplayType.LTR,
                            Name = refugeResource.ResourceLanguage1.Name,
                            Notes = refugeResource.ResourceLanguage1.Notes,
                            Phone = refugeResource.ResourceLanguage1.Phone,
                            CultureInfo = Contants.EnglishUS
                        },
                        new RefugeResourcesLanguage()
                        {
                            Address = refugeResource.ResourceLanguage2.Address,
                            DisplayType = LanguageDisplayType.RTL,
                            Name = refugeResource.ResourceLanguage2.Name,
                            Notes = refugeResource.ResourceLanguage2.Notes,
                            CultureInfo = Contants.Arabic
                        }
                    },
                }).Entity;

                if (refugeResource.Types != null)
                {
                    foreach (var type in refugeResource.Types)
                    {
                        _context.RefugeResourceResourceType.Add(new RefugeResourceResourceType() { RefugeResourceId = resource.ResourceId, ResourceTypeId = (int)type });
                    }
                }

                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }


            return View(refugeResource);
        }

        // GET: RefugeResources/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var refugeResource = await _context.RefugeResources
                                            .Include(x => x.PrimaryResourceType)
                                            .Include(x => x.Languages)
                                            .Include(x => x.ResourceTypes)
                                            .SingleOrDefaultAsync(x => x.ResourceId == id);


            if (refugeResource == null)
                return NotFound();

            var refugeResourceVm = RefugeResourceViewModel.FromModel(refugeResource, SupportedCultures.GetCultureInfo(Contants.Arabic));

            return View(refugeResourceVm);
        }

        // POST: RefugeResources/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, RefugeResourceViewModel refugeResource)
        {
            if (id != refugeResource.ResourceId)
            {
                return NotFound();
            }

            ValidateResource(refugeResource);

            if (ModelState.IsValid)
            {
                try
                {
                    var resource = await _context.RefugeResources.Include(x => x.PrimaryResourceType)
                                            .Include(x => x.ResourceTypes)
                                            .SingleOrDefaultAsync(x => x.ResourceId == id);

                    if (resource == null)
                    {
                        return NotFound();
                    }

                    resource.PrimaryResourceTypeId = (int)refugeResource.PrimaryType;
                    resource.Longitude = refugeResource.Posistion.Longitude;
                    resource.Latitude = refugeResource.Posistion.Latitude;

                    var englishLanguage = await _context.RefugeResourcesLanguages
                                                        .SingleOrDefaultAsync(x => x.RefugeResourceResourceId == resource.ResourceId
                                                                                && x.CultureInfo == Contants.EnglishUS);
                    var araibic = await _context.RefugeResourcesLanguages
                                                        .SingleOrDefaultAsync(x => x.RefugeResourceResourceId == resource.ResourceId
                                                                                && x.CultureInfo == Contants.Arabic);

                    UpdateLanguage(refugeResource.ResourceLanguage1, englishLanguage);
                    UpdateLanguage(refugeResource.ResourceLanguage2, araibic);

                    var currentTypes = resource.ResourceTypes.Select(x => (ResourceTypes)x.ResourceTypeId).ToList();

                    // Make sure we're not trying to enumerate over null
                    if (refugeResource.Types == null)
                    {
                        refugeResource.Types = new List<ResourceTypes>();
                    }

                    var typesNotSelected = currentTypes.Except(refugeResource.Types).ToList();
                    foreach (var resourceTypese in typesNotSelected)
                    {
                        var refugeResourceResourceType = resource.ResourceTypes.First(x => x.ResourceTypeId == (int)resourceTypese);
                        resource.ResourceTypes.Remove(refugeResourceResourceType);
                    }

                    var newTypesSelected = refugeResource.Types.Except(currentTypes).ToList();
                    foreach (var type in newTypesSelected)
                    {

UrbanRefuge.Web/Views/RefugeResources/Create.cshtml
@model UrbanRefuge.Web.ViewModels.RefugeResourceViewModel
@using UrbanRefuge.Web.ViewModels

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Refuge Resource</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="ResourceLanguage1.Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ResourceLanguage1.Name" class="form-control" />
                <span asp-validation-for="ResourceLanguage1.Name" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Arabic Name</label>
            <div class="col-md-10">
                <input asp-for="ResourceLanguage2.Name" class="form-control rtl" />
                <span asp-validation-for="ResourceLanguage2.Name" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Posistion.Latitude" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Posistion.Latitude" class="form-control" />
                <span asp-validation-for="Posistion.Latitude" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Posistion.Longitude" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Posistion.Longitude" class="form-control" />
                <span asp-validation-for="Posistion.Longitude" class="text-danger" />
            </div>
        </div>

       <div class="form-group">
            <label asp-for="PrimaryType" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="PrimaryType" class="form-control" asp-items="Html.GetEnumSelectList<ResourceTypes>()"></select>
            </div>
        </div>

        <div class="form-group">
                <label asp-for="Types" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <select asp-for="Types" multiple class="form-control" asp-items="Html.GetEnumSelectList<ResourceTypes>()"></select>
                </div>
            </div>

        <div class="form-group">
            <label asp-for="ResourceLanguage1.Address" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="ResourceLanguage1.Address" class="form-control" rows="4"></textarea>
                <span asp-validation-for="ResourceLanguage1.Address" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Arabic Address</label>
            <div class="col-md-10">
                <textarea asp-for="ResourceLanguage2.Address" class="form-control rtl" rows="4"></textarea>
                <span asp-validation-for="ResourceLanguage2.Address" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="ResourceLanguage1.Phone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ResourceLanguage1.Phone" class="form-control" />
                <span asp-validation-for="ResourceLanguage1.Phone" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="ResourceLanguage1.Notes" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="ResourceLanguage1.Notes" class="form-control"  rows="3"></textarea>
                <span asp-validation-for="ResourceLanguage1.Notes" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Arabic Notes</label>
            <div class="col-md-10">
                <textarea asp-for="ResourceLanguage2.Notes" class="form-control rtl" rows="3" ></textarea>
                <span asp-validation-for="ResourceLanguage2.Notes" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UrbanRefuge.Web/Views/RefugeResources/Delete.cshtml
@model UrbanRefuge.Web.ViewModels.RefugeResourceViewModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>@Model.ResourceLanguage1.Name</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ResourceLanguage1.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ResourceLanguage1.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PrimaryType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PrimaryType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

UrbanRefuge.Web/Views/RefugeResources/Details.cshtml
@model UrbanRefuge.Web.ViewModels.RefugeResourceViewModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>@Model.ResourceLanguage1.Name</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ResourceLanguage1.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ResourceLanguage1.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResourceLanguage2.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ResourceLanguage2.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrimaryType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PrimaryType)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Posistion.Latitude)
            @Html.DisplayNameFor(model => model.Posistion.Longitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Posistion.Latitude)
            @Html.DisplayFor(model => model.Posistion.Longitude)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.ResourceLanguage1.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ResourceLanguage1.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResourceLanguage2.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ResourceLanguage2.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResourceLanguage1.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ResourceLanguage1.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResourceLanguage1.Notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ResourceLanguage1.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResourceLanguage2.Notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ResourceLanguage2.Notes)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ResourceId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

UrbanRefuge.Web/Views/RefugeResources/Edit.cshtml
@model UrbanRefuge.Web.ViewModels.RefugeResourceViewModel
@using UrbanRefuge.Web.ViewModels

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>@Model.ResourceLanguage1.Name</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ResourceId" />
        <div class="form-group">
            <label asp-for="ResourceLanguage1.Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ResourceLanguage1.Name" class="form-control" />
                <span asp-validation-for="ResourceLanguage1.Name" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Arabic Name</label>
            <div class="col-md-10">
                <input asp-for="ResourceLanguage2.Name" class="form-control rtl" />
                <span asp-validation-for="ResourceLanguage2.Name" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Posistion.Latitude" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Posistion.Latitude" class="form-control" />
                <span asp-validation-for="Posistion.Latitude" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Posistion.Longitude" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Posistion.Longitude" class="form-control" />
                <span asp-validation-for="Posistion.Longitude" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="PrimaryType" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="PrimaryType" class="form-control" asp-items="Html.GetEnumSelectList<ResourceTypes>()"></select>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Types" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="Types" multiple class="form-control" asp-items="Html.GetEnumSelectList<ResourceTypes>()"></select>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="ResourceLanguage1.Address" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="ResourceLanguage1.Address" class="form-control" rows="4"></textarea>
                <span asp-validation-for="ResourceLanguage1.Address" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Arabic Address</label>
            <div class="col-md-10">
                <textarea asp-for="ResourceLanguage2.Address" class="form-control rtl" rows="4"></textarea>
                <span asp-validation-for="ResourceLanguage2.Address" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="ResourceLanguage1.Phone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ResourceLanguage1.Phone" class="form-control" />
                <span asp-validation-for="ResourceLanguage1.Phone" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="ResourceLanguage1.Notes" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="ResourceLanguage1.Notes" class="form-control" rows="3"></textarea>
                <span asp-validation-for="ResourceLanguage1.Notes" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Arabic Notes</label>
            <div class="col-md-10">
                <textarea asp-for="ResourceLanguage2.Notes" class="form-control rtl" rows="3"></textarea>
                <span asp-validation-for="ResourceLanguage2.Notes" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UrbanRefuge.Web/Views/RefugeResources/Index.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Internal
@model UrbanRefuge.Web.ViewModels.RefugeResourcePagedViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-action="Index">
    <p>
        Find by name: @Html.TextBox("query", Model.Query)
        <input type="submit" value="Search" class="btn btn-default" />
    </p>
</form>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Type</th>
                <th>
                    Lat
                </th>
                <th>
                    Long
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Resources)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ResourceLanguage1.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PrimaryType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Posistion.Latitude)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Posistion.Longitude)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ResourceId">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ResourceId">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ResourceId">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <cs-pager cs-paging-pagesize="@Model.Paging.ItemsPerPage"
              cs-paging-pagenumber="@Model.Paging.CurrentPage"
              cs-paging-totalitems="@Model.Paging.TotalItems"
              asp-route-query= "@Model.Query"
              cs-pagenumber-param="page"
              asp-controller="RefugeResources"
              asp-action="Index"></cs-pager>